development:
  adapter: mysql2
  database: kisanbhai_dev
  username: root
  password:

test:
  adapter: mysql2
  database: kisanbhai_test
  username: root
  password:

production:
  adapter: mysql2
  database: kisanbhai_prod
  username: root
  password:
